local monitor = peripheral.find("monitor")
monitor.setTextColor(colors.black)
monitor.setBackgroundColor(colors.lightGray)
local monx, mony = monitor.getSize()
monitor.clear()
monitor.setCursorPos(monx / 2 - 16, 5)
monitor.write("explore,fight and buy,find the boss")
monitor.setCursorPos(monx / 4 - 2, mony / 2 - 1)
monitor.write("store")
monitor.setCursorPos(monx - monx / 4 - 2, mony / 2 - 1)
monitor.write("arena")
monitor.setCursorPos(monx / 4 - 2, mony / 2 + 1)
monitor.blit("__^__", "bbfbb", "bbbbb")
monitor.setCursorPos(monx - monx / 4 - 2, mony / 2 + 1)
monitor.blit("__^__", "bbfbb", "bbbbb")
