local monitor = peripheral.find("monitor")
monitor.setTextColor(colors.black)
monitor.setBackgroundColor(colors.lightGray)
local monx, mony = monitor.getSize()
monitor.clear()
monitor.setCursorPos(monx / 2 - 10, mony / 4 + mony / 8 - 1)
monitor.write("Welcome to our dungeon")
monitor.setCursorPos(monx / 2 - 11, mony / 4 + mony / 8 + 1)
monitor.write("Click right mouse button")
monitor.setCursorPos(monx / 2 - 11, mony / 4 + mony / 8 + 2)
monitor.write("to interact with monitor")
monitor.setCursorPos(monx - monx / 8, 2)
monitor.blit("_____", "bbbbb", "bbbbb")
monitor.setCursorPos(monx - monx / 8, 3)
monitor.blit("_-->_", "bfffb", "bbbbb")
monitor.setCursorPos(monx - monx / 8, 4)
monitor.blit("_____", "bbbbb", "bbbbb")


